name: NBT-API
main: me.choco.nbt.NBTAPI
version: 1.0
description: A library to assist developers in modifying custom NBT data for ItemStacks, Entities and TileEntities
author: 2008Choco
commands:
    itemnbt:
      description: A method to modify item NBT data
      usage: /<command> <set|remove|check>