name: NBT-API
main: me.choco.nbt.NBTAPI
version: 1.0
description: A library to assist developers in modifying custom NBT data for ItemStacks and TileEntities
author: 2008Choco
commands:
    itemnbt:
      description: Test the NBT API
      usage: /<command>